# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/cmake-gui

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mykyta/projects/vm

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mykyta/projects/vm

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mykyta/projects/vm/CMakeFiles /home/mykyta/projects/vm/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mykyta/projects/vm/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named vm

# Build rule for target.
vm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vm
.PHONY : vm

# fast build rule for target.
vm/fast:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/build
.PHONY : vm/fast

src/Assembler.o: src/Assembler.cpp.o
.PHONY : src/Assembler.o

# target to build an object file
src/Assembler.cpp.o:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/Assembler.cpp.o
.PHONY : src/Assembler.cpp.o

src/Assembler.i: src/Assembler.cpp.i
.PHONY : src/Assembler.i

# target to preprocess a source file
src/Assembler.cpp.i:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/Assembler.cpp.i
.PHONY : src/Assembler.cpp.i

src/Assembler.s: src/Assembler.cpp.s
.PHONY : src/Assembler.s

# target to generate assembly for a file
src/Assembler.cpp.s:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/Assembler.cpp.s
.PHONY : src/Assembler.cpp.s

src/Assign.o: src/Assign.cpp.o
.PHONY : src/Assign.o

# target to build an object file
src/Assign.cpp.o:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/Assign.cpp.o
.PHONY : src/Assign.cpp.o

src/Assign.i: src/Assign.cpp.i
.PHONY : src/Assign.i

# target to preprocess a source file
src/Assign.cpp.i:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/Assign.cpp.i
.PHONY : src/Assign.cpp.i

src/Assign.s: src/Assign.cpp.s
.PHONY : src/Assign.s

# target to generate assembly for a file
src/Assign.cpp.s:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/Assign.cpp.s
.PHONY : src/Assign.cpp.s

src/Bytecode.o: src/Bytecode.cpp.o
.PHONY : src/Bytecode.o

# target to build an object file
src/Bytecode.cpp.o:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/Bytecode.cpp.o
.PHONY : src/Bytecode.cpp.o

src/Bytecode.i: src/Bytecode.cpp.i
.PHONY : src/Bytecode.i

# target to preprocess a source file
src/Bytecode.cpp.i:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/Bytecode.cpp.i
.PHONY : src/Bytecode.cpp.i

src/Bytecode.s: src/Bytecode.cpp.s
.PHONY : src/Bytecode.s

# target to generate assembly for a file
src/Bytecode.cpp.s:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/Bytecode.cpp.s
.PHONY : src/Bytecode.cpp.s

src/Ctor.o: src/Ctor.cpp.o
.PHONY : src/Ctor.o

# target to build an object file
src/Ctor.cpp.o:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/Ctor.cpp.o
.PHONY : src/Ctor.cpp.o

src/Ctor.i: src/Ctor.cpp.i
.PHONY : src/Ctor.i

# target to preprocess a source file
src/Ctor.cpp.i:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/Ctor.cpp.i
.PHONY : src/Ctor.cpp.i

src/Ctor.s: src/Ctor.cpp.s
.PHONY : src/Ctor.s

# target to generate assembly for a file
src/Ctor.cpp.s:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/Ctor.cpp.s
.PHONY : src/Ctor.cpp.s

src/Dynamic.o: src/Dynamic.cpp.o
.PHONY : src/Dynamic.o

# target to build an object file
src/Dynamic.cpp.o:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/Dynamic.cpp.o
.PHONY : src/Dynamic.cpp.o

src/Dynamic.i: src/Dynamic.cpp.i
.PHONY : src/Dynamic.i

# target to preprocess a source file
src/Dynamic.cpp.i:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/Dynamic.cpp.i
.PHONY : src/Dynamic.cpp.i

src/Dynamic.s: src/Dynamic.cpp.s
.PHONY : src/Dynamic.s

# target to generate assembly for a file
src/Dynamic.cpp.s:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/Dynamic.cpp.s
.PHONY : src/Dynamic.cpp.s

src/File.o: src/File.cpp.o
.PHONY : src/File.o

# target to build an object file
src/File.cpp.o:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/File.cpp.o
.PHONY : src/File.cpp.o

src/File.i: src/File.cpp.i
.PHONY : src/File.i

# target to preprocess a source file
src/File.cpp.i:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/File.cpp.i
.PHONY : src/File.cpp.i

src/File.s: src/File.cpp.s
.PHONY : src/File.s

# target to generate assembly for a file
src/File.cpp.s:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/File.cpp.s
.PHONY : src/File.cpp.s

src/GarbageCollector.o: src/GarbageCollector.cpp.o
.PHONY : src/GarbageCollector.o

# target to build an object file
src/GarbageCollector.cpp.o:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/GarbageCollector.cpp.o
.PHONY : src/GarbageCollector.cpp.o

src/GarbageCollector.i: src/GarbageCollector.cpp.i
.PHONY : src/GarbageCollector.i

# target to preprocess a source file
src/GarbageCollector.cpp.i:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/GarbageCollector.cpp.i
.PHONY : src/GarbageCollector.cpp.i

src/GarbageCollector.s: src/GarbageCollector.cpp.s
.PHONY : src/GarbageCollector.s

# target to generate assembly for a file
src/GarbageCollector.cpp.s:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/GarbageCollector.cpp.s
.PHONY : src/GarbageCollector.cpp.s

src/Heap.o: src/Heap.cpp.o
.PHONY : src/Heap.o

# target to build an object file
src/Heap.cpp.o:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/Heap.cpp.o
.PHONY : src/Heap.cpp.o

src/Heap.i: src/Heap.cpp.i
.PHONY : src/Heap.i

# target to preprocess a source file
src/Heap.cpp.i:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/Heap.cpp.i
.PHONY : src/Heap.cpp.i

src/Heap.s: src/Heap.cpp.s
.PHONY : src/Heap.s

# target to generate assembly for a file
src/Heap.cpp.s:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/Heap.cpp.s
.PHONY : src/Heap.cpp.s

src/Hexdump.o: src/Hexdump.cpp.o
.PHONY : src/Hexdump.o

# target to build an object file
src/Hexdump.cpp.o:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/Hexdump.cpp.o
.PHONY : src/Hexdump.cpp.o

src/Hexdump.i: src/Hexdump.cpp.i
.PHONY : src/Hexdump.i

# target to preprocess a source file
src/Hexdump.cpp.i:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/Hexdump.cpp.i
.PHONY : src/Hexdump.cpp.i

src/Hexdump.s: src/Hexdump.cpp.s
.PHONY : src/Hexdump.s

# target to generate assembly for a file
src/Hexdump.cpp.s:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/Hexdump.cpp.s
.PHONY : src/Hexdump.cpp.s

src/Iterator.o: src/Iterator.cpp.o
.PHONY : src/Iterator.o

# target to build an object file
src/Iterator.cpp.o:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/Iterator.cpp.o
.PHONY : src/Iterator.cpp.o

src/Iterator.i: src/Iterator.cpp.i
.PHONY : src/Iterator.i

# target to preprocess a source file
src/Iterator.cpp.i:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/Iterator.cpp.i
.PHONY : src/Iterator.cpp.i

src/Iterator.s: src/Iterator.cpp.s
.PHONY : src/Iterator.s

# target to generate assembly for a file
src/Iterator.cpp.s:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/Iterator.cpp.s
.PHONY : src/Iterator.cpp.s

src/Machine.o: src/Machine.cpp.o
.PHONY : src/Machine.o

# target to build an object file
src/Machine.cpp.o:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/Machine.cpp.o
.PHONY : src/Machine.cpp.o

src/Machine.i: src/Machine.cpp.i
.PHONY : src/Machine.i

# target to preprocess a source file
src/Machine.cpp.i:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/Machine.cpp.i
.PHONY : src/Machine.cpp.i

src/Machine.s: src/Machine.cpp.s
.PHONY : src/Machine.s

# target to generate assembly for a file
src/Machine.cpp.s:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/Machine.cpp.s
.PHONY : src/Machine.cpp.s

src/MachineCalls.o: src/MachineCalls.cpp.o
.PHONY : src/MachineCalls.o

# target to build an object file
src/MachineCalls.cpp.o:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/MachineCalls.cpp.o
.PHONY : src/MachineCalls.cpp.o

src/MachineCalls.i: src/MachineCalls.cpp.i
.PHONY : src/MachineCalls.i

# target to preprocess a source file
src/MachineCalls.cpp.i:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/MachineCalls.cpp.i
.PHONY : src/MachineCalls.cpp.i

src/MachineCalls.s: src/MachineCalls.cpp.s
.PHONY : src/MachineCalls.s

# target to generate assembly for a file
src/MachineCalls.cpp.s:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/MachineCalls.cpp.s
.PHONY : src/MachineCalls.cpp.s

src/Main.o: src/Main.cpp.o
.PHONY : src/Main.o

# target to build an object file
src/Main.cpp.o:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/Main.cpp.o
.PHONY : src/Main.cpp.o

src/Main.i: src/Main.cpp.i
.PHONY : src/Main.i

# target to preprocess a source file
src/Main.cpp.i:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/Main.cpp.i
.PHONY : src/Main.cpp.i

src/Main.s: src/Main.cpp.s
.PHONY : src/Main.s

# target to generate assembly for a file
src/Main.cpp.s:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/Main.cpp.s
.PHONY : src/Main.cpp.s

src/Object.o: src/Object.cpp.o
.PHONY : src/Object.o

# target to build an object file
src/Object.cpp.o:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/Object.cpp.o
.PHONY : src/Object.cpp.o

src/Object.i: src/Object.cpp.i
.PHONY : src/Object.i

# target to preprocess a source file
src/Object.cpp.i:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/Object.cpp.i
.PHONY : src/Object.cpp.i

src/Object.s: src/Object.cpp.s
.PHONY : src/Object.s

# target to generate assembly for a file
src/Object.cpp.s:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/Object.cpp.s
.PHONY : src/Object.cpp.s

src/Registers.o: src/Registers.cpp.o
.PHONY : src/Registers.o

# target to build an object file
src/Registers.cpp.o:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/Registers.cpp.o
.PHONY : src/Registers.cpp.o

src/Registers.i: src/Registers.cpp.i
.PHONY : src/Registers.i

# target to preprocess a source file
src/Registers.cpp.i:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/Registers.cpp.i
.PHONY : src/Registers.cpp.i

src/Registers.s: src/Registers.cpp.s
.PHONY : src/Registers.s

# target to generate assembly for a file
src/Registers.cpp.s:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/Registers.cpp.s
.PHONY : src/Registers.cpp.s

src/Relational.o: src/Relational.cpp.o
.PHONY : src/Relational.o

# target to build an object file
src/Relational.cpp.o:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/Relational.cpp.o
.PHONY : src/Relational.cpp.o

src/Relational.i: src/Relational.cpp.i
.PHONY : src/Relational.i

# target to preprocess a source file
src/Relational.cpp.i:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/Relational.cpp.i
.PHONY : src/Relational.cpp.i

src/Relational.s: src/Relational.cpp.s
.PHONY : src/Relational.s

# target to generate assembly for a file
src/Relational.cpp.s:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/Relational.cpp.s
.PHONY : src/Relational.cpp.s

src/Stack.o: src/Stack.cpp.o
.PHONY : src/Stack.o

# target to build an object file
src/Stack.cpp.o:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/Stack.cpp.o
.PHONY : src/Stack.cpp.o

src/Stack.i: src/Stack.cpp.i
.PHONY : src/Stack.i

# target to preprocess a source file
src/Stack.cpp.i:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/Stack.cpp.i
.PHONY : src/Stack.cpp.i

src/Stack.s: src/Stack.cpp.s
.PHONY : src/Stack.s

# target to generate assembly for a file
src/Stack.cpp.s:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/Stack.cpp.s
.PHONY : src/Stack.cpp.s

src/Types.o: src/Types.cpp.o
.PHONY : src/Types.o

# target to build an object file
src/Types.cpp.o:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/Types.cpp.o
.PHONY : src/Types.cpp.o

src/Types.i: src/Types.cpp.i
.PHONY : src/Types.i

# target to preprocess a source file
src/Types.cpp.i:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/Types.cpp.i
.PHONY : src/Types.cpp.i

src/Types.s: src/Types.cpp.s
.PHONY : src/Types.s

# target to generate assembly for a file
src/Types.cpp.s:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/Types.cpp.s
.PHONY : src/Types.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... vm"
	@echo "... src/Assembler.o"
	@echo "... src/Assembler.i"
	@echo "... src/Assembler.s"
	@echo "... src/Assign.o"
	@echo "... src/Assign.i"
	@echo "... src/Assign.s"
	@echo "... src/Bytecode.o"
	@echo "... src/Bytecode.i"
	@echo "... src/Bytecode.s"
	@echo "... src/Ctor.o"
	@echo "... src/Ctor.i"
	@echo "... src/Ctor.s"
	@echo "... src/Dynamic.o"
	@echo "... src/Dynamic.i"
	@echo "... src/Dynamic.s"
	@echo "... src/File.o"
	@echo "... src/File.i"
	@echo "... src/File.s"
	@echo "... src/GarbageCollector.o"
	@echo "... src/GarbageCollector.i"
	@echo "... src/GarbageCollector.s"
	@echo "... src/Heap.o"
	@echo "... src/Heap.i"
	@echo "... src/Heap.s"
	@echo "... src/Hexdump.o"
	@echo "... src/Hexdump.i"
	@echo "... src/Hexdump.s"
	@echo "... src/Iterator.o"
	@echo "... src/Iterator.i"
	@echo "... src/Iterator.s"
	@echo "... src/Machine.o"
	@echo "... src/Machine.i"
	@echo "... src/Machine.s"
	@echo "... src/MachineCalls.o"
	@echo "... src/MachineCalls.i"
	@echo "... src/MachineCalls.s"
	@echo "... src/Main.o"
	@echo "... src/Main.i"
	@echo "... src/Main.s"
	@echo "... src/Object.o"
	@echo "... src/Object.i"
	@echo "... src/Object.s"
	@echo "... src/Registers.o"
	@echo "... src/Registers.i"
	@echo "... src/Registers.s"
	@echo "... src/Relational.o"
	@echo "... src/Relational.i"
	@echo "... src/Relational.s"
	@echo "... src/Stack.o"
	@echo "... src/Stack.i"
	@echo "... src/Stack.s"
	@echo "... src/Types.o"
	@echo "... src/Types.i"
	@echo "... src/Types.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

